HA2/KnotenKanten/config/routes.rb
KnotenKanten::Application.routes.draw do
  resources :kantens

  resources :knotens

end

HA2/KnotenKanten/app/models/kanten.rb
class Kanten < ActiveRecord::Base
end

HA2/KnotenKanten/app/models/knoten.rb
class Knoten < ActiveRecord::Base
end

HA2/KnotenKanten/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

HA2/KnotenKanten/app/controllers/kantens_controller.rb
class KantensController < ApplicationController
  # GET /kantens
  # GET /kantens.xml
  def index
    @kantens = Kanten.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @kantens }
    end
  end

  # GET /kantens/1
  # GET /kantens/1.xml
  def show
    @kanten = Kanten.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @kanten }
    end
  end

  # GET /kantens/new
  # GET /kantens/new.xml
  def new
    @kanten = Kanten.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @kanten }
    end
  end

  # GET /kantens/1/edit
  def edit
    @kanten = Kanten.find(params[:id])
  end

  # POST /kantens
  # POST /kantens.xml
  def create
    @kanten = Kanten.new(params[:kanten])

    respond_to do |format|
      if @kanten.save
        format.html { redirect_to(@kanten, :notice => 'Kanten was successfully created.') }
        format.xml  { render :xml => @kanten, :status => :created, :location => @kanten }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @kanten.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /kantens/1
  # PUT /kantens/1.xml
  def update
    @kanten = Kanten.find(params[:id])

    respond_to do |format|
      if @kanten.update_attributes(params[:kanten])
        format.html { redirect_to(@kanten, :notice => 'Kanten was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @kanten.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /kantens/1
  # DELETE /kantens/1.xml
  def destroy
    @kanten = Kanten.find(params[:id])
    @kanten.destroy

    respond_to do |format|
      format.html { redirect_to(kantens_url) }
      format.xml  { head :ok }
    end
  end
end

HA2/KnotenKanten/app/controllers/knotens_controller.rb
class KnotensController < ApplicationController
  # GET /knotens
  # GET /knotens.xml
  def index
    @knotens = Knoten.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @knotens }
    end
  end

  # GET /knotens/1
  # GET /knotens/1.xml
  def show
    @knoten = Knoten.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @knoten }
    end
  end

  # GET /knotens/new
  # GET /knotens/new.xml
  def new
    @knoten = Knoten.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @knoten }
    end
  end

  # GET /knotens/1/edit
  def edit
    @knoten = Knoten.find(params[:id])
  end

  # POST /knotens
  # POST /knotens.xml
  def create
    @knoten = Knoten.new(params[:knoten])

    respond_to do |format|
      if @knoten.save
        format.html { redirect_to(@knoten, :notice => 'Knoten was successfully created.') }
        format.xml  { render :xml => @knoten, :status => :created, :location => @knoten }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @knoten.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /knotens/1
  # PUT /knotens/1.xml
  def update
    @knoten = Knoten.find(params[:id])

    respond_to do |format|
      if @knoten.update_attributes(params[:knoten])
        format.html { redirect_to(@knoten, :notice => 'Knoten was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @knoten.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /knotens/1
  # DELETE /knotens/1.xml
  def destroy
    @knoten = Knoten.find(params[:id])
    @knoten.destroy

    respond_to do |format|
      format.html { redirect_to(knotens_url) }
      format.xml  { head :ok }
    end
  end
end

HA2/KnotenKanten/app/helpers/application_helper.rb
module ApplicationHelper
end

HA2/KnotenKanten/app/helpers/kantens_helper.rb
module KantensHelper
end

HA2/KnotenKanten/app/helpers/knotens_helper.rb
module KnotensHelper
end

HA2/KnotenKanten/app/views/kantens/_form.html.erb
<%= form_for(@kanten) do |f| %>
  <% if @kanten.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@kanten.errors.count, "error") %> prohibited this kanten from being saved:</h2>

      <ul>
      <% @kanten.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :knoten1_id %><br />
    <%= f.text_field :knoten1_id %>
  </div>
  <div class="field">
    <%= f.label :knoten2_id %><br />
    <%= f.text_field :knoten2_id %>
  </div>
  <div class="field">
    <%= f.label :kantenlaenge %><br />
    <%= f.text_field :kantenlaenge %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

HA2/KnotenKanten/app/views/kantens/edit.html.erb
<h1>Editing kanten</h1>

<%= render 'form' %>

<%= link_to 'Show', @kanten %> |
<%= link_to 'Back', kantens_path %>

HA2/KnotenKanten/app/views/kantens/index.html.erb
<h1>Listing kantens</h1>

<table>
  <tr>
    <th>Knoten1</th>
    <th>Knoten2</th>
    <th>Kantenlaenge</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @kantens.each do |kanten| %>
  <tr>
    <td><%= kanten.knoten1_id %></td>
    <td><%= kanten.knoten2_id %></td>
    <td><%= kanten.kantenlaenge %></td>
    <td><%= link_to 'Show', kanten %></td>
    <td><%= link_to 'Edit', edit_kanten_path(kanten) %></td>
    <td><%= link_to 'Destroy', kanten, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Kanten', new_kanten_path %>

HA2/KnotenKanten/app/views/kantens/new.html.erb
<h1>New kanten</h1>

<%= render 'form' %>

<%= link_to 'Back', kantens_path %>

HA2/KnotenKanten/app/views/kantens/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Knoten1:</b>
  <%= @kanten.knoten1_id %>
</p>

<p>
  <b>Knoten2:</b>
  <%= @kanten.knoten2_id %>
</p>

<p>
  <b>Kantenlaenge:</b>
  <%= @kanten.kantenlaenge %>
</p>


<%= link_to 'Edit', edit_kanten_path(@kanten) %> |
<%= link_to 'Back', kantens_path %>

HA2/KnotenKanten/app/views/knotens/_form.html.erb
<%= form_for(@knoten) do |f| %>
  <% if @knoten.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@knoten.errors.count, "error") %> prohibited this knoten from being saved:</h2>

      <ul>
      <% @knoten.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

HA2/KnotenKanten/app/views/knotens/edit.html.erb
<h1>Editing knoten</h1>

<%= render 'form' %>

<%= link_to 'Show', @knoten %> |
<%= link_to 'Back', knotens_path %>

HA2/KnotenKanten/app/views/knotens/index.html.erb
<h1>Listing knotens</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @knotens.each do |knoten| %>
  <tr>
    <td><%= knoten.name %></td>
    <td><%= link_to 'Show', knoten %></td>
    <td><%= link_to 'Edit', edit_knoten_path(knoten) %></td>
    <td><%= link_to 'Destroy', knoten, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Knoten', new_knoten_path %>

HA2/KnotenKanten/app/views/knotens/new.html.erb
<h1>New knoten</h1>

<%= render 'form' %>

<%= link_to 'Back', knotens_path %>

HA2/KnotenKanten/app/views/knotens/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @knoten.name %>
</p>


<%= link_to 'Edit', edit_knoten_path(@knoten) %> |
<%= link_to 'Back', knotens_path %>

HA2/KnotenKanten/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>KnotenKanten</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>